server:
   port: 8761

eureka:
   instance:
       hostname: 192.168.101.70
       prefer-ip-address: true
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: wolf  # 用户名  
    password: abc123   # 用户密码 