 eureka:
 
     instance:
         prefer-ip-address: true
         status-page-url: http://192.168.101.70:8762/swagger-ui.html
         metadata-map:
             getUserList: {"url":"user/getAll","desc":"获取用户列表","method":"get"}
             getUserById: {"url":"user/getUserById","desc":"根据用户id获取用户信息","method":"get"}
             updateUser: {"url":"user/update","desc":"更新用户信息","method":"put"}
     client:
         serviceUrl:
             defaultZone: http://admin:admin@192.168.101.70:8761/eureka/
 server:
     port: 8762
 spring:
     datasource:
         url: jdbc:mysql://localhost:3306/spring_eureka
         username: root
         password: 123
         driverClassName: com.mysql.jdbc.Driver
     jpa: 
         properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
         database: MYSQL
         show-sql: false
         hibernate:
             ddl-auto: update
             naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
     application:
         name: service-helloworld
     devtools:
         restart:
            enabled:  false
         additional-paths: src/main/resources
# security:
#  basic:
#    enabled: true    #启用SpringSecurity的安全配置项
#  user:
#    name: jmxjava    #认证用户名
#    password: jmxhello #认证密码
#    role:              #授权角色
#    - USER
         