server:
   port: 8761

eureka:
   instance:
       hostname: 192.168.101.70
       prefer-ip-address: true
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/