server:
  port: 5678
spring:
  application:
    name: sidecar
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@192.168.101.70:8761/eureka/
    healthcheck: false
  instance:
         hostname: 192.168.101.70
         ip-address: 192.168.101.70
         status-page-url: http://${eureka.instance.hostname}:8200/llkOA/api/index.do
         prefer-ip-address: true
         instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  add-host-header: true
sidecar:
  port: 8080
  health-uri: http://${eureka.instance.hostname}:${sidecar.port}/llkOA/health.do
logging:
  level:
    root: debug
endpoints:
  actuator:
    enabled: true
hystrix: 
  command: 
    default: 
      execution: 
        timeout: 
          enabled: false